"""Create new tables

Revision ID: 584b57a947e2
Revises: 
Create Date: 2025-08-15 11:35:16.019970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584b57a947e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_seller_id'), 'seller', ['id'], unique=False)
    op.create_table('shipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('destination', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLACED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', name='shipmentstatus'), nullable=False),
    sa.Column('estimated_delivery', sa.DateTime(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_id'), 'shipment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_id'), table_name='shipment')
    op.drop_table('shipment')
    op.drop_index(op.f('ix_seller_id'), table_name='seller')
    op.drop_table('seller')
    # ### end Alembic commands ###
