"""Created and updated tables

Revision ID: 962e7e6800f6
Revises: 584b57a947e2
Create Date: 2025-08-16 10:41:32.883129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962e7e6800f6'
down_revision: Union[str, Sequence[str], None] = '584b57a947e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_partner',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('serviceable_zip_codes', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('max_handling_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_delivery_partner_id'), 'delivery_partner', ['id'], unique=False)
    op.add_column('seller', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('shipment', sa.Column('delivery_partner_id', sa.UUID(), nullable=True))
    op.add_column('shipment', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'shipment', 'delivery_partner', ['delivery_partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_column('shipment', 'created_at')
    op.drop_column('shipment', 'delivery_partner_id')
    op.drop_column('seller', 'created_at')
    op.drop_index(op.f('ix_delivery_partner_id'), table_name='delivery_partner')
    op.drop_table('delivery_partner')
    # ### end Alembic commands ###
